[".config/xmonad/xmonad"]
    type = "git-repo"
    url = "https://github.com/rynoV/xmonad"
[".config/xmonad/xmonad-contrib"]
    type = "git-repo"
    url = "https://github.com/rynoV/xmonad-contrib"
["scripts/xmobar"]
    type = "git-repo"
    url = "https://github.com/rynoV/xmobar"
[".config/ranger/plugins/ranger-archives"]
    type = "git-repo"
    url = "https://github.com/maximtrp/ranger-archives"
[".config/ranger/plugins/zoxide"]
    type = "git-repo"
    url = "https://github.com/jchook/ranger-zoxide"