[".config/xmonad/xmonad"]
    type = "git-repo"
    url = "https://github.com/xmonad/xmonad"
[".config/xmonad/xmonad-contrib"]
    type = "git-repo"
    url = "https://github.com/xmonad/xmonad-contrib"
["scripts/xmobar"]
    type = "git-repo"
    url = "https://github.com/jaor/xmobar"
