#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xset s off # Disable screen saver
xset r rate 200 30 # Set key repeat delay and rate
xsetroot -cursor_name left_ptr # Set cursor style

modprobe ddcci
modprobe i2c_dev

export XDG_CURRENT_DESKTOP=xmonad
export XDG_SESSION_DESKTOP=xmonad
autorandr --change # Configure monitors before xmonad starts
variety &
# hidamari --background &
picom --no-vsync &
exec xmonad 2> $HOME/.xsession-errors
