use-grammars = { only = [ "haskell", "html" ] }

[[language]]
name = "haskell"
auto-format = true

[[grammar]]
name = "haskell"
source = { git = "https://github.com/tree-sitter/tree-sitter-haskell", rev = "ca0a13f1acb60cf32e74cced3cb623b6c70fa77c" }

[[language]]
name = "purescript"
scope = "scope.purescript"
injection-regex = "^purescript$"
file-types = ["purs"]
comment-token = "--"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "purescript-language-server", args = ["--stdio"] }
roots = ["packages.dhall", "spago.dhall"]
auto-format = true
grammar = "haskell"
diagnostic-severity = "Warning"